name: E2E on Chrome

on: deployment_status

defaults:
  run:
    working-directory: guess-the-move-frontend

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          working-directory: guess-the-move-frontend
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
